### ISSUE TITLE
Version of hackages 0.0.7, while hackjam-react uses 0.0.8

### ISSUE THREAD

**Issue by svdoever** [hackages/hackages#1]
Hi Davy,

https://github.com/hackages/hackjam-react uses version 0.0.8, while this repository is on version 0.0.7.
If I look at the npm package it is at version 0.0.8 as well - https://www.npmjs.com/package/hackages, does the repository contain the latest code base?

**Comment by davyengone** [comment]
Hey Serge, I forgot to push the tags... now it's fixed :) :
